config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  root to: "home#index"

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      get "/sessions", to: "sessions#create"
      get "/me", to: "users#me"
      get "/entries/search", to: "entries#search"
      get "/project_files/download_all", to: "project_files#download_all"
    end
  end

  # Service Worker Routes
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline.html" => "service_worker#offline"

  get "/progress/total" => "progress#total"

  get "project_files/download", to: "project_files#download_all", as: :download_all_file

  resources :project_files, controller: "project_files", type: "ProjectFile" do
    get "output", to: "project_files#output", as: :output
    post "batch", to: "project_files#batch_update_entry", as: :batch_update_entry
  end

  %i[event night_conversation grathmeld_conversation cosmosphere_random gift_install misc].each do |type|
    resources type, controller: "project_files", type: type.to_s.camelize do
      get "output", to: "project_files#output", as: :output
      post "batch", to: "project_files#batch_update_entry", as: :batch_update_entry
    end
    get "#{type}/goto/:name", to: "project_files#goto", type: type.to_s.camelize, constraints: {name: /.+?(?:json)?/}
  end

  resources :entries do
    get "hints", to: "entries#hints"
  end
  # get "project_files/:name", controller: "project_files",
  #                            action: :show,
  #                            format: false,
  #                            defaults: { format: "html" },
  #                            as: :project_filename, constraints: { name: /\d+.evd.txt/ }

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  } do
    devise_scope :user do
      get "edit", to: "users/registrations#edit", as: :edit_user_registration
      get "sign_in", to: "users/sessions#new", as: :new_user_session
      get "sign_out", to: "users/sessions#destroy", as: :destroy_user_session
    end
  end
  authenticate :user, ->(u) { u.admin? } do
    mount AuditLog::Engine => "/audit-log"
    draw :madmin
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_paper_trail
  enum status: {draft: 0, accept: 1, double_check: 2, final_check: 3, finished: 4}
  belongs_to :user, optional: true
  belongs_to :project_file
  after_save :update_associates

  after_update_commit do
    broadcast_replace_to "main-app", target: "entry_list_item_#{id}",
      partial: "entries/entry_list_item",
      locals: {entry: self, active: true}
    broadcast_replace_to "main-app", target: "entry_#{id}", partial: "entries/entry", locals: {entry: self}
  end

  include MeiliSearch::Rails
  extend Pagy::Meilisearch

  meilisearch enqueue: true do
    attribute %i[source english chinese]
  end

  def update_associates
    project_file.touch if project_file.present?
  end

  def narrator
    Narrator.find_by(narrator_id: narrator_id)
  end

  # def hints
  #   @hints = []
  #   @nm ||= Natto::MeCab.new(dicdir: "/usr/lib/mecab/dic/mecab-ipadic-neologd")
  #   @tokens = @nm.parse(source).split("\n").to_a[0...-1].map do |n|
  #     n = n.split("\t")
  #     next if n.size == 1
  #     next if n[1].include?("記号")
  #
  #     n[0]
  #   end.compact
  #   @hints.append @tokens
  #   @hints.append Noun.where(source: @tokens).pluck("source", "chinese")
  #   @hints.append Narrator.where(narrator_source: @tokens).pluck("narrator_source", "narrator_chinese")
  #   @hints
  # end

  def humanize_status
    case status
    when "accept"
      "一校"
    when "double_check"
      "二校"
    when "final_check"
      "三校"
    when "finished"
      "完成"
    else
      chinese.empty? ? "空白" : "草稿"
    end
  end

  def history_change(limit: 10)
    AuditLog::Log
      .where(action: "update_entry", record_type: "Entry", record_id: id)
      .order("id DESC")
      .limit(limit)
      .pluck(:user_id, :payload, :created_at)
      .map { |data| {user: User.find_by(id: data[0])&.name, data: data[1], time: data[2]} }
  end

  def prefix
    [location, narrator_id].map do |i|
      return "" if i.blank?

      "#{i},"
    end.join
  end

  def text
    string = chinese.blank? ? source : chinese
    string.to_line
  end

  class << self
    def replace_all(source, chinese)
      where(source: source).update_all(chinese: chinese)
    end

    def replace_all_term(search, original, replace)
      where("source ILIKE ?", "%#{search}%").each do |entry|
        entry.chinese = entry.chinese.gsub(original, replace)
        entry.save
      end
    end
  end
end

app/controllers/api/v1/entries_controller.rb
class Api::V1::EntriesController < Api::V1::BaseController
  before_action :api_authenticate!
  before_action :search_params, only: :search

  def search
    column = search_params.fetch :column, "source"
    text = search_params.fetch :text, nil
    @entries = Entry.where("#{column}": text).limit(search_params.fetch(:limit, 10))
  end

  private

  def search_params
    params.permit(:text, :column, :fuzzy, :limit)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!, only: %i[update]
  before_action :set_entry, only: %i[show edit update]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
    # authorize! @entry
  end

  # GET /entries/new
  # def new
  #   @entry = Entry.new
  # end

  # GET /entries/1/edit
  def edit
    @nouns = Noun.where("? ~ source", @entry.source)
  end

  def hints
    @entry = Entry.find(params[:entry_id])
    @hints =
      Entry
        .joins(:project_file)
        .where.not(id: @entry.id)
        .where("(source <->> '#{@entry.source}') < 0.7")
        .select(:name, :source, :chinese, "(source <->> '#{@entry.source}') as distance")
        .order("distance")
        .limit(5)
        .to_a.map(&:serializable_hash)
        .uniq { |p| p["chinese"] }
        .each { |p| p.delete("id") }

    render partial: "entries/hints", locals: {hints: @hints}
  end

  # POST /entries or /entries.json
  # def create
  #   @entry = Entry.new(entry_params)
  #
  #   respond_to do |format|
  #     if @entry.save
  #       format.html { redirect_to @entry, notice: "Entry was successfully created." }
  #       format.json { render :show, status: :created, location: @entry }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @entry.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    # authorize! @entry
    previous_chinese = @entry.chinese
    status_params = params.fetch(:entry).permit(:status)
    status_update = false
    respond_to do |format|
      if status_params && status_params["status"] != @entry.status
        if status_params["status"] == Entry.statuses.keys[-1] && !current_user.admin?
          status_params = {}
        else
          status_update = true
        end
      end
      if previous_chinese == entry_params.fetch(:chinese) && !status_update
        format.html { redirect_to @entry, notice: "" }
        format.json { render :show, status: :ok, location: @entry }
      elsif @entry.update(entry_params.merge(status_params))
        if previous_chinese != @entry.chinese
          audit! :update_entry, @entry, payload: entry_params.permit(:chinese).merge(previous_chinese: previous_chinese)
        end
        if status_update
          audit! :update_entry, @entry, payload: {message: "条目状态更改为 #{Entry.human_enum_name(:status, @entry.status)}"}
        end
        format.html { redirect_to @entry, notice: "条目更新成功" }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
    # rescue_from ActionPolicy::Unauthorized do
    #   redirect_to new_user_session_path
    # end
  end

  # DELETE /entries/1 or /entries/1.json
  # def destroy
  #   @entry.destroy
  #   respond_to do |format|
  #     format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params["entry"]["chinese"] = params["entry"]["chinese"].gsub(/(?<!\r)\n/, "\r\n")
    params.fetch(:entry, {}).merge(user_id: current_user.id).permit(:chinese, :user_id)
  end
end

app/controllers/madmin/entries_controller.rb
module Madmin
  class EntriesController < Madmin::ResourceController
  end
end

app/helpers/api/v1/entries_helper.rb
module Api::V1::EntriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<% cache entry do %>
  <turbo-frame id="<%= dom_id entry %>" class="flex flex-col gap-2" data-controller="entry-details" data-action="resize@window->entry-details#resize_textarea">
    <div class="flex flex-col sm:flex-row gap-0.5 sm:gap-2">
      <% width = entry.english.blank? ? "sm:w-1/2" : "sm:w-1/3" %>
      <div class="<%= width %> flex flex-col flex-grow-0">
        <label for="source">原文</label>
        <textarea id="source" lang="ja" class="textarea textarea-bordered w-full h-auto p-1 sm:p-2 overflow-hidden hidden-scrollbar !bg-gray-100 dark:!bg-gray-700 !border-black text-base"><%= entry.source %></textarea>
      </div>
      <% unless entry.english.blank? %>
      <div class="<%= width %> flex flex-col flex-shrink">
        <label for="english">英文翻译</label>
        <textarea id="english" lang="en" class="textarea textarea-bordered w-full h-auto p-1 sm:p-2 overflow-hidden hidden-scrollbar !bg-gray-100 dark:!bg-gray-700 !border-black text-base"><%= entry.english %></textarea>
      </div>
      <% end %>
      <div class="<%= width %> flex flex-col flex-shrink">
        <label for="chinese">中文翻译</label>
        <textarea id="chinese" lang="zh-Hans" class="textarea textarea-bordered w-full h-auto p-1 sm:p-2 overflow-hidden hidden-scrollbar !bg-gray-100 dark:!bg-gray-700 !border-black text-base font-cn"><%= entry.chinese %></textarea>
      </div>
    </div>
  </turbo-frame>
<% end %>

app/views/entries/_entry_list.html.erb
<turbo-frame id="entry_list" class="flex flex-col font-sans" data-controller="entry-list-component">
  <div id="entry_list_header" class="flex flex-row justify-start font-semibold gap-x-0.5 sm:gap-x-2">
    <div class="shrink-0 sm:w-32 flex flex-col sm:flex-row">
      <div class="w-7 sm:w-12 shrink-0 text-xs sm:text-sm sm:mr-2">状态</div>
      <% unless entries.filter{ |entry| entry.narrator_id != "0" }.none? %>
        <div class="w-12 sm:w-16 shrink-0 text-xs sm:text-sm mr-1 sm:mr-3">叙述者</div>
      <% end %>
    </div>
    <div class="w-full text-xs sm:text-sm">文本</div>
    <div class="w-2 text-xs self-end invisible" id="entry-list-next" data-action="click->entry-list-component#next">N</div>
  </div>
  <div id="entry_list_body" class="flex flex-col h-60 overflow-auto resize-vertical gap-y-1 style-resizer" data-action="resize->entry-list-component#resizeBody">
    <%# cache entries do %>
      <% entries.each do |entry| %>
        <%= render EntryListItemComponent.new(entry) %>
      <% end %>
    <%# end %>
  </div>
  <div class="flex flex-col sm:flex-row sm:items-center text-xs sm:text-sm mt-2 space-x-4">
    <div class="flex flex-row items-center justify-between space-x-2">
      <div class="">标题: <%= @project_file.display_name %></div>
      <div class="">文件名: <%= @project_file.name %></div>
      <% if current_user %>
      <a href="<%= project_file_output_path @project_file.id %>"
        class="ml-4 inline-flex items-center text-blue-700 dark:text-blue-300 border border-black dark:border-gray-100 rounded p-1"
        target="_blank"
      > <span class="hidden sm:block">下载</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
      </a>
      <% end %>
    </div>
    <% if current_user %>
    <form class="inline-flex items-center space-x-2">
      <span>批量修改状态:</span>
      <%= select "", "status", status_select_list.collect { |status| [Entry.human_enum_name(:status, status), status] },
                { include_blank: true }, class: "ml-4 w-24 h-8 px-2 py-1 rounded-sm dark:bg-gray-500 text-sm" %>
      <button
        class="btn btn-outline btn-sm"
        data-file-id="<%= @project_file.id %>"
        data-reflex="click->EntryListComponent#batch_update_status"
        data-reflex-dataset="combined"
      >
        更新
      </button>
    </form>
    <% end %>
  </div>
</turbo-frame>

app/views/entries/_entry_list_item.html.erb
<% active ||= false %>
<%= render(EntryListItemComponent.new(entry, active: active)) %>

app/views/entries/_form.html.erb
<%= form_for @entry, data: { "turbo-frame": "entry-details", "controller": "entry-form" },
             html: { class: "flex flex-col" } do |form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% @entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-2 sm:flex-row-reverse">
    <div id="hint" class="sm:w-3/5">
      提示:
      <div class="flex flex-col overflow-y-scroll hidden-scrollbar">
        <div class="text-sm ">
          <% unless @entry.narrator.blank? %>
            <div class="text-sm">
              叙述者：【<%= @entry.narrator.narrator_chinese %>】
            </div>
          <% end %>
          <% cache @nouns do %>
            <% @nouns.each do |noun| %>
              <div class="font-cn">
                <span class="">
                  <%= "［#{noun.leixing}］#{noun.source}：#{noun.chinese}" %><%= noun.comment.blank? ? "" : "（#{noun.comment}）" %>
                </span>
              </div>
            <% end %>
          <% end %>
        </div>
        <turbo-frame id="entry_edit_hints" class="max-h-[10rem] overflow-y-scroll"
                     src="<%= entry_hints_path @entry %>">
        </turbo-frame>
      </div>
    </div>
    <div class="sm:w-2/5 flex flex-col gap-1">
      <%= form.label :chinese, "中文翻译" %>
      <div class="relative">
        <%= form.text_area :chinese,
                           class: "textarea textarea-bordered w-full h-auto rounded border-1 border-blue-400 hover:border-blue-400 dark:bg-gray-600 px-2 py-1 font-noto-sans block overflow-hidden text-base",
                           data: { action: "keydown->entry-form#keydown input->entry-form#autoResize" },
                           disable: "#{current_user.nil? ? 'true' : 'false'}",
                           lang: "zh-Hans" %>
        <div class="absolute ml-[13.5em] border-l-2 border-accent/70 h-full top-0">
        </div>
      </div>
      <% unless current_user.nil? %>
        <div id="entry_form_actions" class="">
          <%= form.label :status, "更改状态" %>
          <%= form.select :status, status_select_list.collect { |status| [Entry.human_enum_name(:status, status), status] },
                          { selected: 'double_check' }, class: "ml-4 w-24 h-8 px-2 py-1 rounded-sm dark:bg-gray-500 text-sm" %>
        </div>
        <div class="actions">
          <%= form.submit "更新条目", class: "rounded px-3 py-1 border-res bg-blue-300 shadow dark:bg-indigo-600",
                          submitId: "entry_#{ @entry.id }", data: { action: "editor#submit" } %>
        </div>
      <% end %>
    </div>
  </div>
  <% unless @entry.history_change.none? %>
    <turbo-frame id="entry_<%= @entry.id %>_log" class="mt-2 flex flex-col text-sm">
      <p>条目[<%= @entry.id %>] 变更记录</p>
      <% @entry.history_change.each do |history| %>
        <div class="flex flex-row gap-x-3 gap-y-1">
          <div><%= history.fetch(:time)&.in_time_zone("Asia/Shanghai").strftime('%Y-%m-%d %H:%M:%S') %></div>
          <div>[<%= history.fetch(:user, "未知") %>]</div>
          <div><%= history.fetch(:data)["message"] ? history.fetch(:data)["message"] : history.fetch(:data)["chinese"] %></div>
        </div>
      <% end %>
    </turbo-frame>
  <% end %>
<% end %>

app/views/entries/_hints.html.erb
<turbo-frame id="entry_edit_hints">
  <% if hints.any? %>
    <% hints.each do |hint| %>
      <div class="flex flex-row gap-2 max-w-3xl">
        <div class="text-sm w-fit">
          <%= hint["name"] %>
        </div>
        <div class="flex flex-col flex-no-wrap">
          <div class="text-xs">
            <span class="text-sm" lang="ja"></span> <%= hint["source"] %>
          </div>
          <div class="text-sm">
            <span class="text-sm" lang="zh-Hans"></span> <%= hint["chinese"] %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</turbo-frame>

app/views/entries/edit.html.erb
<turbo-frame id="entry-edit" class="flex flex-col rounded-md shadow p-2 mx-2 bg-gray-100 dark:bg-gray-700 dark:text-gray-200">
  <%= render 'entries/form' %>
</turbo-frame>

app/views/entries/index.html.erb
<turbo-frame id="entry_list" class="bg-gray-100 flex flex-col px-4 py-2 font-sans" data-controller="entry-list-component" >
  <div id="entry_list_header" class="flex flex-row justify-start font-semibold gap-x-2">
    <div class="w-12">状态</div>
    <div class="w-16">编号</div>
    <div class="w-full">文本</div>
  </div>
  <div id="entry_list_body" class="flex flex-col max-h-72 overflow-auto">
    <% entries.each do |entry| %>
      <div id="project_file_<%= @project_file.id %>_entry_<%= entry.id %>" class="flex flex-row justify-start gap-x-2" data-action="click->entry-list-component#click">
        <div class="w-12 text-sm"><%= entry.status == "finished" ? "完成": "草稿" %></div>
        <div class="w-16"><%= entry.location %></div>
        <div class="w-64 truncate"><%= entry.source %></div>
        <div class="w-64 mr-6 truncate"><%= entry.english %></div>
        <div class="w-64 truncate"><%= entry.chinese %></div>
      </div>
    <% end %>
  </div>
</turbo-frame>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<% cache @entry do %>
  <turbo-frame id="entry-details" class="flex flex-col rounded-md shadow p-2 mx-2 bg-gray-100 dark:bg-gray-700 dark:text-gray-200">
    <% unless @entry.user_id.nil? %>
      <div class="">
        最后编辑: <%= @entry.user.nickname %>
      </div>
    <% end %>
    <%= render @entry %>
  </turbo-frame>
<!--  <turbo-frame id="entry-edit"-->
<!--               class="flex flex-col rounded-md shadow p-2 mx-2 bg-gray-100 dark:bg-gray-700 dark:text-gray-200"-->
<!--               src="<%#= edit_entry_path(@entry) %>"></turbo-frame>-->
<% end %>