config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  root to: "home#index"

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      get "/sessions", to: "sessions#create"
      get "/me", to: "users#me"
      get "/entries/search", to: "entries#search"
      get "/project_files/download_all", to: "project_files#download_all"
    end
  end

  # Service Worker Routes
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline.html" => "service_worker#offline"

  get "/progress/total" => "progress#total"

  get "project_files/download", to: "project_files#download_all", as: :download_all_file

  resources :project_files, controller: "project_files", type: "ProjectFile" do
    get "output", to: "project_files#output", as: :output
    post "batch", to: "project_files#batch_update_entry", as: :batch_update_entry
  end

  %i[event night_conversation grathmeld_conversation cosmosphere_random gift_install misc].each do |type|
    resources type, controller: "project_files", type: type.to_s.camelize do
      get "output", to: "project_files#output", as: :output
      post "batch", to: "project_files#batch_update_entry", as: :batch_update_entry
    end
    get "#{type}/goto/:name", to: "project_files#goto", type: type.to_s.camelize, constraints: {name: /.+?(?:json)?/}
  end

  resources :entries do
    get "hints", to: "entries#hints"
  end
  # get "project_files/:name", controller: "project_files",
  #                            action: :show,
  #                            format: false,
  #                            defaults: { format: "html" },
  #                            as: :project_filename, constraints: { name: /\d+.evd.txt/ }

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  } do
    devise_scope :user do
      get "edit", to: "users/registrations#edit", as: :edit_user_registration
      get "sign_in", to: "users/sessions#new", as: :new_user_session
      get "sign_out", to: "users/sessions#destroy", as: :destroy_user_session
    end
  end
  authenticate :user, ->(u) { u.admin? } do
    mount AuditLog::Engine => "/audit-log"
    draw :madmin
  end
end

app/models/project_file.rb
class ProjectFile < ApplicationRecord
  default_scope -> { order("id") }
  enum status: {working: 0, done: 1}
  has_many :entries, dependent: :destroy

  after_update_commit do
    broadcast_replace_to "main-app",
      target: "project_file_#{id}_progress",
      partial: "project_files/progress",
      locals: {project_file: instance_of?(ProjectFile) ? self : becomes(ProjectFile)}
  end

  include MeiliSearch::Rails
  meilisearch do
    attribute %i[name title status]
  end

  def to_txt(source: false)
    get_text = source ? ->(entry) { entry.source.to_line } : ->(entry) { entry.text }
    entries.order(:index).map do |entry|
      entry.prefix + get_text[entry]
    end.join("\n\n").concat("\n")
  end

  def progress
    status = entries.group(:status).size
    empty = entries.where(chinese: "").where.not(status: 4).size
    draft = status.fetch("draft", 0) - entries.where(status: 0, chinese: "").size
    draft = 0 if draft.negative?
    proofreading = status.fetch("accept", 0) 
    finished = status.fetch("finished", 0) + status.fetch("double_check", 0) + status.fetch("final_check", 0)
    {filename: name, empty: empty, draft: draft, proofreading: proofreading, finished: finished}
  end

  def page_num(options = {})
    column = options[:by] || :id
    order = options[:order] || :asc
    per = options[:per] || self.class.default_per_page

    operator = ((order == :asc) ? "<=" : ">=")
    (self.class
         .where("#{column} #{operator} ?", read_attribute(column))
         .order("#{column} #{order}").count.to_f / per).ceil
  end

  def display_name
    return name if title.nil?

    "#{name} - #{title}"
  end

  class << self
    def download_all(source = false)
      dir = Dir.mktmpdir("ProjectFile_")
      begin
        all.order(:id).each do |project_file|
          next if project_file.entries.order(:index).where.not(chinese: "").count.zero?

          File.open("#{dir}/#{project_file.name}", "w", encoding: "UTF-8") do |file|
            file.write(project_file.to_txt(source: source))
          end
        end
        file_list = `ls -1d #{dir}/*`.split.join(" ")
        file = "#{Rails.root}/public/tmp/ProjectFile_#{source ? "_source_" : ""}#{Time.now.to_i}.zip"
        `zip -9 -j #{file} #{file_list}`
      ensure
        RemoveTmpDirJob.perform_later(dir)
        RemoveTmpDirJob.set(wait: 10.minutes).perform_later(file)
      end
      file.remove("#{Rails.root}/public")
    end
  end
end

app/controllers/api/v1/project_files_controller.rb
class Api::V1::ProjectFilesController < Api::V1::BaseController
  before_action :api_authenticate!

  def download_all
    source = params.fetch(:source, "false") == "true"

    render json: { path: ProjectFile.download_all(source) }
  end

end

app/controllers/madmin/project_files_controller.rb
module Madmin
  class ProjectFilesController < Madmin::ResourceController
  end
end

app/controllers/project_files_controller.rb
class ProjectFilesController < ApplicationController
  before_action :authenticate_user!, only: %i[download_all batch_update_entry edit update]
  before_action :set_project_file, only: %i[show edit update]

  # GET /project_files or /project_files.json
  def index
    @file_id = params[:file_id] ? params[:file_id].to_i : project_file_type.first&.id
    @page = if params[:page]
      params[:page]&.to_i
    elsif params[:file_id].nil? && params[:page].nil?
      1
    else
      project_file_type.find(params[:file_id]).page_num(per: 25)
    end
    @pagy, @project_files = pagy(project_file_type, page: @page, items: 25)
    @frame = params[:frame] || "_top"
  end

  # GET /project_files/1 or /project_files/1.json
  def show
    @file_id = @project_file.id
    @entries = @project_file.entries.order(:index)

    if params[:entry] && @file_id == (entry = Entry.find_by(id: params.fetch(:entry)))&.project_file_id
      @entry = entry
    end

    if @project_file.nil?
      render file: "public/404.html", status: :not_found, layout: false
      return
    end

    @entry ||= @entries.first
  end

  # download single file
  # GET /projects_files/1/output
  def output
    @project_file = project_file_type.find(params[:project_file_id])
    send_data(@project_file.to_txt, filename: @project_file.name)
  end

  # download all project file
  # GET /projects_files/download
  def download_all
    source = params.fetch(:source, "false") == "true"

    redirect_to ProjectFile.download_all(source), layout: false
  end

  # POST /project_files/1/batch or /project_files/1/batch.json
  def batch_update_entry
    @project_file = project_file_type.find(params[:project_file_id])
    @status = (params.fetch(:status)[0] if current_user.admin?) || nil
    render file: "public/404.html", status: :not_found, layout: false and return if @project_file.nil?

    uploaded_file = params[:uploaded_file]
    render file: "public/404.html", status: :not_found, layout: false and return if uploaded_file.nil?

    unless %w[text/plain text/csv application/vnd.ms-excel].include?(uploaded_file.content_type) && uploaded_file.original_filename == @project_file.name
      respond_to do |format|
        flash[:alert] = "文件类型或文件名不匹配"
        format.html { redirect_to @project_file, status: :unprocessable_entity }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end and return
    end

    data = File.open(uploaded_file.tempfile, "r", encoding: "utf-8").read
    data = data.split(/\r\n|(?<!\r)\n/).reject(&:empty?)
    if data.count != @project_file.entries.count
      respond_to do |format|
        flash[:alert] = "文件条目数量不符"
        format.html { redirect_to @project_file, status: :unprocessable_entity }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end and return
    end

    entries = @project_file.entries.order(:index)
    data.each_with_index do |line, index|
      entry = entries[index]
      next if entry.status.to_i >= 2

      location, narrator_id = line.scan(/\A[^,]+,[-\d]+,/)[0]&.split(",") || ["", ""]
      text = line.remove("#{location},#{narrator_id},")
        .gsub("CR", "\r\n")
        .gsub(/(?!{)((IM\d{2}|SC\d{2}|1X|VB\d{2}|CS\d{2}|#[01][ A-Za-z0-9_\-!.]+(##)?)+)/) { |w| "{#{w}}" }
      next unless location == entry.location && narrator_id == entry.narrator_id &&
        text != entry.source && text.to_halfwidth != entry.english && text != entry.chinese && !text.blank?

      entry.chinese = text
      entry.status = @status || 0
      entry.user_id = current_user.id
      if entry.save
        audit! :update_entry, entry,
          payload: {message: "从文件批量导入条目，状态变更为#{entry.status}，新文本：#{entry.chinese}"}
      end
    end

    respond_to do |format|
      format.html { redirect_to @project_file, notice: "文件更新成功" }
      format.json { render :show, status: :ok, location: @project_file }
    end
  end

  # GET /project_files/new
  # def new
  #   @project_file = ProjectFile.new
  # end

  # GET /project_files/1/edit
  def edit
  end

  # POST /project_files or /project_files.json
  # def create
  #   @project_file = ProjectFile.new(project_file_params)
  #
  #   respond_to do |format|
  #     if @project_file.save
  #       format.html { redirect_to @project_file, notice: "Project file was successfully created." }
  #       format.json { render :show, status: :created, location: @project_file }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @project_file.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /project_files/1 or /project_files/1.json
  def update
    respond_to do |format|
      if @project_file.update(project_file_params)
        format.html { redirect_to @project_file, notice: "Project file was successfully updated." }
        format.json { render :show, status: :ok, location: @project_file }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  # # DELETE /project_files/1 or /project_files/1.json
  # def destroy
  #   @project_file.destroy
  #   respond_to do |format|
  #     format.html { redirect_to project_files_url, notice: "Project file was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project_file
    @project_file = project_file_type.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_file_params
    params.fetch(:project_file, {})
  end

  def project_file_types
    %w[ProjectFile Event NightConversation GrathmeldConversation CosmosphereRandom GiftInstall Misc]
  end

  def project_file_type
    params[:type].constantize if params[:type].in? project_file_types
  end
end

app/helpers/project_files_helper.rb
module ProjectFilesHelper
  def project_files_index_path(*args)
    url_for({ controller: :project_files, action: :index, type: @project_file.class.to_s }.merge(args[0]))
  end
end

app/views/project_files/_form.html.erb
<%= form_with(model: project_file) do |form| %>
  <% if project_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_file.errors.count, "error") %> prohibited this project_file from being saved:</h2>

      <ul>
        <% project_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_files/_progress.html.erb
<%= render(FileProgressComponent.new(project_file: project_file)) %>

app/views/project_files/edit.html.erb
<!--<h1>Editing Project File</h1>-->

<%= render 'form', project_file: @project_file %>

<!--<%#= link_to 'Show', @project_file %> |-->
<%#= link_to 'Back', project_files_path %>

app/views/project_files/index.html.erb
<% content_for :title, "[Page #{@page+1}] - ProjectFile" %>

<%= render(FileListComponent.new(@project_files, @progress, file_id: @file_id,
                                 page: @page, frame: @frame, pagy: @pagy)) %>

app/views/project_files/new.html.erb
<h1>New Project File</h1>

<%= render 'form', project_file: @project_file %>

<%= link_to 'Back', project_files_path %>

app/views/project_files/show.html.erb
<% content_for :title, @project_file.name %>

<div class="lg:flex" x-data="{ file_list: 'close' }">
  <%= turbo_stream_from "main-app" %>

  <button id="nav-switch" type="button" class="fixed z-50 bottom-3 right-4 w-10 h-10 rounded-full bg-gray-900 text-white block lg:hidden" @click="file_list = 'open'">
    <span class="sr-only">Open file list</span>
    <svg width="24" height="24" fill="none" class="absolute top-1/2 left-1/2 -mt-3 -ml-3 transition duration-300 transform"
         :class="{ 'opacity-0 scale-80': file_list === 'open' }"
    >
      <path d="M4 8h16M4 16h16" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg>
    <svg width="24" height="24" fill="none" class="absolute top-1/2 left-1/2 -mt-3 -ml-3 transition duration-300 transform"
         :class="{ 'opacity-0 scale-80': file_list === 'close' }">
      <path d="M6 18L18 6M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg>
  </button>

  <div id="sidebar"
       :class="{ 'hidden': file_list === 'close' }"
       class="fixed z-40 inset-0 flex-none h-full bg-base-100 bg-opacity-25 w-full lg:static lg:h-auto lg:overflow-y-visible lg:pt-0 lg:w-72 xl:w-80 lg:block transition duration-300 transform"
  >
    <turbo-frame id="file_list" src="<%= project_files_index_path(file_id: @file_id, frame: "editor", page: @project_file.page_num(per: 25)) %>" @click.away="file_list = 'close'"
                 class="font-sans flex flex-col bg-gray-100 px-2 py-1 lg:w-auto lg:shadow-md lg:mt-2 lg:ml-2 dark:bg-gray-800 lg:dark:mt-0 lg:dark:ml-0"
    >
    </turbo-frame>
  </div>

  <div id="content-wrapper" class="min-w-0 w-full flex-auto lg:static lg:max-h-full lg:overflow-visible"
       :class="{ 'overflow-hidden max-h-screen fixed': file_list === 'open' }">
    <turbo-frame id="editor" class="pt-2 flex flex-col flex-auto space-y-2" data-controller="editor">
      <% if current_user.nil? %>
        <%= render(LoginPromptComponent.new) %>
      <% end %>
      <div class="rounded-md shadow mx-2 px-1 md:px-4 py-2 bg-gray-100 dark:bg-gray-700 dark:text-gray-200 ">
        <%= render(partial: "entries/entry_list", locals: { entries: @entries }) %>
      </div>
      <turbo-frame id="entry-details"
                   class="flex flex-col rounded-md shadow p-1 sm:p-2 text-sm sm:text-md mx-2 min-h-[5rem] bg-gray-100 dark:bg-gray-700 dark:text-gray-200"
                   src="<%= entry_path @entry %>"
      ></turbo-frame>
      <turbo-frame id="entry-edit"
                   class="flex flex-col rounded-md shadow p-1 sm:p-2 mx-2 min-h-[11rem] bg-gray-100 dark:bg-gray-700 dark:text-gray-200"
                   src="<%= edit_entry_path @entry %>"
      ></turbo-frame>
      <% unless current_user.nil? %>
        <%= render(EntryBatchImportComponent.new(project_file: @project_file, current_user: current_user)) %>
      <% end %>
    </turbo-frame>
  </div>

</div>