config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  root to: "home#index"

  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      get "/sessions", to: "sessions#create"
      get "/me", to: "users#me"
      get "/entries/search", to: "entries#search"
      get "/project_files/download_all", to: "project_files#download_all"
    end
  end

  # Service Worker Routes
  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline.html" => "service_worker#offline"

  get "/progress/total" => "progress#total"

  get "project_files/download", to: "project_files#download_all", as: :download_all_file

  resources :project_files, controller: "project_files", type: "ProjectFile" do
    get "output", to: "project_files#output", as: :output
    post "batch", to: "project_files#batch_update_entry", as: :batch_update_entry
  end

  %i[event night_conversation grathmeld_conversation cosmosphere_random gift_install misc].each do |type|
    resources type, controller: "project_files", type: type.to_s.camelize do
      get "output", to: "project_files#output", as: :output
      post "batch", to: "project_files#batch_update_entry", as: :batch_update_entry
    end
    get "#{type}/goto/:name", to: "project_files#goto", type: type.to_s.camelize, constraints: {name: /.+?(?:json)?/}
  end

  resources :entries do
    get "hints", to: "entries#hints"
  end
  # get "project_files/:name", controller: "project_files",
  #                            action: :show,
  #                            format: false,
  #                            defaults: { format: "html" },
  #                            as: :project_filename, constraints: { name: /\d+.evd.txt/ }

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  } do
    devise_scope :user do
      get "edit", to: "users/registrations#edit", as: :edit_user_registration
      get "sign_in", to: "users/sessions#new", as: :new_user_session
      get "sign_out", to: "users/sessions#destroy", as: :destroy_user_session
    end
  end
  authenticate :user, ->(u) { u.admin? } do
    mount AuditLog::Engine => "/audit-log"
    draw :madmin
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" sizes="512x512" href="/icon-512x512.png">
    <link rel="apple-touch-icon" href="/icon-192x192.png">
    <meta name="theme-color" content="#57507D"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="歌颂之丘 - 魔塔大陆汉化协作站 | By寂听 使用Rails构建">
    <link rel="stylesheet" href="https://fonts.googleapis.cn/css2?family=Noto+Sans+SC:wght@300;400;500;700&amp;display=swap">
    <meta name="environment" content="<%= Rails.env.to_s %>">
    <meta name="release" content="<%= Sentry.configuration&.release.to_s %>">
    <% if ENV["SENTRY_FRONTEND_DSN"].present? %>
      <meta name="sentry-dsn" content="<%= ENV.fetch("SENTRY_FRONTEND_DSN", "") %>">
      <%= vite_javascript_tag "sentry" %>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application', "data-turbo-track": "reload", media: "all" %>
  </head>
  <body class="">
    <div class="h-full w-full">
      <nav class="sticky top-0 z-40 lg:z-50 w-full max-w-8xl h-12 mx-auto bg-gray-100 dark:bg-gray-700 flex-none flex flex-row px-2 sm:px-4 py-2 items-center justify-between">
        <div class="flex flex-row space-x-2 items-center">
          <div class="navbar-item hidden" data-controller="service-worker" style="display: none;" hidden>
            <%= image_tag "cloud-check.svg", width: "23px", height: "23px", alt: "", data: { 'service-worker-target':"pageSavedNotice" }, class: "hidden" %>
            <%= image_tag "cloud-download.svg", width: "23px", height: "23px", alt: "", data: { 'service-worker-target':"savingPageNotice" }, class: "" %>
          </div>
          <a href="<%= root_path %>" id="logo" class="inline-flex h-6 rounded-full text-gray-700 dark:text-gray-200 font-bold shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 sm:hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span class="hidden sm:block"><%= t("SingingHill") %></span>
          </a>
          <online-users data-turbo-permanent></online-users>
          <%= yield :nav %>
        </div>

        <div class="flex flex-row space-x-1 md:space-x-3 items-center justify-center">
          <%= yield :nav_right %>
          <div class="text-xs sm:text-sm md:text-base" data-turbo-permanent>
            <%= render(ModalComponent.new(open_text: "搜索", modal_id: "search")) do %>
              <%= render partial: "shared/search" %>
            <% end %>
          </div>
          <div class="text-xs sm:text-sm md:text-base">
            <%= render(ModalComponent.new(open_text: "进度", modal_id: "progress-box")) do %>
              <turbo-frame src="<%= progress_total_path %>" class="flex flex-col dark:text-gray-100 items-center justify-center space-y-2"  id="total_progress">
              </turbo-frame>
            <% end %>
          </div>
          <% if user_signed_in? %>
            <div class="dark:text-gray-100 text-xs sm:text-sm md:text-base truncate">
              <% if current_user != true_user %>
                <%= current_user.name %>(F)
              <% elsif current_user %>
                <%= current_user.name %>
              <% end %>
            </div>
            <div class="inline-block px-1 py-1 text-sm leading-none no-underline text-gray lg:mt-0">
              <div class="relative" data-controller="dropdown" data-dropdown-open-value="false">
                <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="inline-block select-none">
                <span class="flex items-center inline-block appearance-none">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 sm:w-6 sm:h-6 dark:text-gray-100" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                  </svg>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="hidden sm:block w-4 h-4 text-gray-700 fill-current dark:text-gray-100"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"></path></svg>
                </span>
                </div>
                <div data-dropdown-target="menu" class="absolute right-0 hidden mt-2">
                  <div class="overflow-hidden text-right text-gray-900 border border-gray-700 rounded shadow bg-gray-50 dark:bg-gray-700 dark:text-gray-200 dark:border-gray-400 hover:bg-gray-300 hover:dark:bg-gray-500">
                      <%#= link_to "修改用户", edit_user_registration_path, data: { action: "click->dropdown#toggle" }, class: 'no-underline block px-6 py-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-300 hover:dark:bg-gray-500 whitespace-nowrap' %>
                      <%= link_to "总进度", progress_total_path, data: { action: "click->dropdown#toggle" }, class: 'no-underline block px-6 py-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-300 hover:dark:bg-gray-500 whitespace-nowrap' %>
                      <% if current_user&.admin? %>
                        <%= link_to "管理面板", madmin_root_path, data: { action: "click->dropdown#toggle" }, class: 'no-underline block px-6 py-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-300 hover:dark:bg-gray-500 whitespace-nowrap' %>
                        <%= link_to "审计日志", audit_log_path, data: { action: "click->dropdown#toggle" }, class: 'no-underline block px-6 py-3 bg-gray-50 dark:bg-gray-700 hover:bg-gray-300 hover:dark:bg-gray-500 whitespace-nowrap' %>
                      <% end %>
                      <% if current_user != true_user %>
                        <%= button_to "停止伪装", "/madmin/impersonates/stop_impersonating", method: :post, data: { action: "click->dropdown#toggle" }, form_class: "border-t border-gray-700 dark:border-gray-400 hover:bg-gray-300", class: "!border-0 no-underline block !px-6 !py-3 w-full !bg-gray-50 !rounded-none dark:!bg-gray-700 hover:!bg-gray-300 hover:dark:!bg-gray-500 hover:cursor-pointer whitespace-nowrap" %>
                      <% end %>
                      <%= button_to "登出", destroy_user_session_path, method: :delete, data: { action: "click->dropdown#toggle" }, form_class: "border-t border-gray-700 dark:border-gray-400 hover:bg-gray-300", class: "!border-0 no-underline block !px-6 !py-3 w-full !bg-gray-50 !rounded-none dark:!bg-gray-700 hover:!bg-gray-300 hover:dark:!bg-gray-500 hover:cursor-pointer whitespace-nowrap" %>
                  </div>

                </div>
              </div>
            </div>
          <% else %>
            <%= button_to "登录", user_gitlab_omniauth_authorize_path,
                        class: "w-14 h-8 px-1 py-1 rounded-lg shadow-lg bg-gray-300 appearance-none focus:outline-none focus:ring-2 focus:ring-gray-600 dark:bg-indigo-600 dark:text-gray-200 focus:dark:ring-indigo-400 text-center tracking-wide",
                        "data-turbo": "false" %>
          <% end %>
        </div>
      </nav>
<!--      <main class="w-full h-5/6 flex flex-row flex-auto">-->
      <%= turbo_frame_tag "flash", class: "dark:text-gray-200 min-w-8 hidden sm:block" do %>
        <%= render "shared/flash" %>
      <% end %>
      <main class="w-full min-h-screen-12 max-w-8xl mx-auto dark:bg-gray-800">
          <%= yield %>
      </main>
    </div>
  </body>
</html>